parameters:
    weather_cache_namespace: 'weather'
    weather_cache_default_life_time: '100'
    weather_cache_directory: '%kernel.project_dir%/var/'

services:
    app.weather.file_system_cache:
        class: Symfony\Component\Cache\Simple\FilesystemCache
        arguments:
            $namespace: '%weather_cache_namespace%'
            $defaultLifetime: '%weather_cache_default_life_time%'
            $directory: '%weather_cache_directory%'

    app.weather.loader_service:
        class: App\Weather\LoaderService
        public: true
        arguments:
            - '@app.weather.provider_service_manager'
            - '@app.weather.file_system_cache'

    app.weather.provider_service_manager:
      class: App\Weather\ProviderServiceManager
      calls:
          - [addWeatherProvider, ['google', '@app.external_api.google.weather_service']]
          - [addWeatherProvider, ['yahoo', '@app.external_api.yahoo.weather_service']]
